version: '3.4'

services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
    - SA_PASSWORD=xU7AQC8wjMQ5jfChjdjoVaeAkco8
    - ACCEPT_EULA=Y
    ports:
    - "1450:1433"
  api:
    container_name: API
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    depends_on:
    - sqlserver