version: '3.4'

networks:
  enigmanetwork:
    name: enigmanetwork

services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
    - SA_PASSWORD=xU7AQC8wjMQ5jfChjdjoVaeAkco8
    - ACCEPT_EULA=Y
    ports:
    - "1450:1433"
    networks:
    - enigmanetwork
  api:
    container_name: api
    image: ${DOCKER_REGISTRY-}api
    restart: always
    build:
      context: .
      dockerfile: API/Dockerfile
    depends_on:
    - sqlserver
    networks:
    - enigmanetwork